import c4d
from c4d import gui, storage
# this is a simple template writing script for Lumiere Bone Transfer
# the format is simple, string pairs one after another, first is the
# source joint name, second is the target joint name

path = "H:\\hik_template.lum"
ident = 1035326 #file identifier, lumiere bone transfer ID

def write():
    hf=storage.HyperFile()
    if hf.Open(ident, path, c4d.FILEOPEN_WRITE, 0):
        hf.WriteString("Head")
        hf.WriteString("Head")
        hf.WriteString("Hips")
        hf.WriteString("Hips")
        hf.WriteString("LeftArm")
        hf.WriteString("LeftArm")
        hf.WriteString("LeftFoot")
        hf.WriteString("LeftFoot")
        hf.WriteString("LeftForeArm")
        hf.WriteString("LeftForeArm")
        hf.WriteString("LeftHand")
        hf.WriteString("LeftHand")
        hf.WriteString("LeftHandIndex1")
        hf.WriteString("LeftHandIndex1")
        hf.WriteString("LeftHandIndex2")
        hf.WriteString("LeftHandIndex2")
        hf.WriteString("LeftHandIndex3")
        hf.WriteString("LeftHandIndex3")
        hf.WriteString("LeftHandIndex4")
        hf.WriteString("LeftHandIndex4")
        hf.WriteString("LeftHandMiddle1")
        hf.WriteString("LeftHandMiddle1")
        hf.WriteString("LeftHandMiddle2")
        hf.WriteString("LeftHandMiddle2")
        hf.WriteString("LeftHandMiddle3")
        hf.WriteString("LeftHandMiddle3")
        hf.WriteString("LeftHandMiddle4")
        hf.WriteString("LeftHandMiddle4")
        hf.WriteString("LeftHandPinky1")
        hf.WriteString("LeftHandPinky1")
        hf.WriteString("LeftHandPinky2")
        hf.WriteString("LeftHandPinky2")
        hf.WriteString("LeftHandPinky3")
        hf.WriteString("LeftHandPinky3")
        hf.WriteString("LeftHandPinky4")
        hf.WriteString("LeftHandPinky4")
        hf.WriteString("LeftHandRing1")
        hf.WriteString("LeftHandRing1")
        hf.WriteString("LeftHandRing2")
        hf.WriteString("LeftHandRing2")
        hf.WriteString("LeftHandRing3")
        hf.WriteString("LeftHandRing3")
        hf.WriteString("LeftHandRing4")
        hf.WriteString("LeftHandRing4")
        hf.WriteString("LeftHandThumb1")
        hf.WriteString("LeftHandThumb1")
        hf.WriteString("LeftHandThumb2")
        hf.WriteString("LeftHandThumb2")
        hf.WriteString("LeftHandThumb3")
        hf.WriteString("LeftHandThumb3")
        hf.WriteString("LeftHandThumb4")
        hf.WriteString("LeftHandThumb4")
        hf.WriteString("LeftLeg")
        hf.WriteString("LeftLeg")
        hf.WriteString("LeftShoulder")
        hf.WriteString("LeftShoulder")
        hf.WriteString("LeftToeBase")
        hf.WriteString("LeftToeBase")
        hf.WriteString("LeftUpLeg")
        hf.WriteString("LeftUpLeg")
        hf.WriteString("Neck")
        hf.WriteString("Neck")
        hf.WriteString("RightArm")
        hf.WriteString("RightArm")
        hf.WriteString("RightFoot")
        hf.WriteString("RightFoot")
        hf.WriteString("RightForeArm")
        hf.WriteString("RightForeArm")
        hf.WriteString("RightHand")
        hf.WriteString("RightHand")
        hf.WriteString("RightHandIndex1")
        hf.WriteString("RightHandIndex1")
        hf.WriteString("RightHandIndex2")
        hf.WriteString("RightHandIndex2")
        hf.WriteString("RightHandIndex3")
        hf.WriteString("RightHandIndex3")
        hf.WriteString("RightHandIndex4")
        hf.WriteString("RightHandIndex4")
        hf.WriteString("RightHandMiddle1")
        hf.WriteString("RightHandMiddle1")
        hf.WriteString("RightHandMiddle2")
        hf.WriteString("RightHandMiddle2")
        hf.WriteString("RightHandMiddle3")
        hf.WriteString("RightHandMiddle3")
        hf.WriteString("RightHandMiddle4")
        hf.WriteString("RightHandMiddle4")
        hf.WriteString("RightHandPinky1")
        hf.WriteString("RightHandPinky1")
        hf.WriteString("RightHandPinky2")
        hf.WriteString("RightHandPinky2")
        hf.WriteString("RightHandPinky3")
        hf.WriteString("RightHandPinky3")
        hf.WriteString("RightHandPinky4")
        hf.WriteString("RightHandPinky4")
        hf.WriteString("RightHandRing1")
        hf.WriteString("RightHandRing1")
        hf.WriteString("RightHandRing2")
        hf.WriteString("RightHandRing2")
        hf.WriteString("RightHandRing3")
        hf.WriteString("RightHandRing3")
        hf.WriteString("RightHandRing4")
        hf.WriteString("RightHandRing4")
        hf.WriteString("RightHandThumb1")
        hf.WriteString("RightHandThumb1")
        hf.WriteString("RightHandThumb2")
        hf.WriteString("RightHandThumb2")
        hf.WriteString("RightHandThumb3")
        hf.WriteString("RightHandThumb3")
        hf.WriteString("RightHandThumb4")
        hf.WriteString("RightHandThumb4")
        hf.WriteString("RightLeg")
        hf.WriteString("RightLeg")
        hf.WriteString("RightShoulder")
        hf.WriteString("RightShoulder")
        hf.WriteString("RightToeBase")
        hf.WriteString("RightToeBase")
        hf.WriteString("RightUpLeg")
        hf.WriteString("RightUpLeg")
        hf.WriteString("Spine")
        hf.WriteString("Spine")
        hf.WriteString("Spine1")
        hf.WriteString("Spine1")
        hf.WriteString("Spine2")
        hf.WriteString("Spine2")

      
        hf.Close()
    else:
        gui.MessageDialog("Cannot open file to write.")

def read():
    hf=storage.HyperFile()
    hf.Open(ident, path, c4d.FILEOPEN_READ, 0)
    c=hf.ReadString()
    print c #ouput 
    hf.Close()

if __name__=='__main__':
    write()